### ISSUE TITLE
commit 58db6635 is breaking Sal plugins and puppet config

### ISSUE THREAD

**Issue by fuzzycheck** [grahamgilbert/grahamgilbert-mac_facts#6]
Hi,

  commit 58db66355b14c915137add85bb526d5dba46dfce changed the fact mac_laptop to a true/false instead of mac_laptop/mac_desktop. This breaks the Sal plugins. For example:

https://github.com/salopensource/grahamgilbert-plugins/blob/master/encryption/encryption.py

 And also in my Puppet config, I have in the hiera config:

- "%{::osfamily}/%{::mac_laptop}"

  It means I would have to rename a file mac_laptop.yaml to true.yaml.

  Would it be possible to revert his commit? I can't update the mac_facts module in my config because of this.

  Thanks for your help.

Regards,
Fuzzy

**Comment by grahamgilbert** [comment]
This plugin was merged in to Sal core a while ago.

Sent from my iPhone
________________________________

**Comment by grahamgilbert** [comment]
You are also able to pin your puppet file to use the older version if you do not wish to upgrade.
